### ISSUE TITLE
README should say which file format is expected as an input

### ISSUE THREAD

**Issue by saintsjd** [koopjs/koop-filesystem-s3#23]
The README should specify which file format is expected as an input.  Readme says:

    const stream = fs.createReadStream('path/to/file')
          .pipe(s3fs.createWriteStream('filename'))

As a new user, it is not clear to me which file format is expected for `path/to/file` and `filename`. is it geojson? vector tiles? other?

We should add a sentence above the code explaining which file formats are acceptable as inputs.

**Comment by dmfenton** [comment]
Thanks for the feedback @saintsjd. You can use any file path your system will accept, whether that be absolute or relative. We will update the docs to make this more clear. Out of curiosity, what's your use case with this library?

All of the following are valid:
`./file.txt'
`./foo/file.txt`
`file.txt`
`foo/file.txt`
`/foo/file.txt`
`../file.txt`
`../foo/file.txt`
`../../file.txt`
etc

**Comment by dmfenton** [comment]
Sorry I misread your question. You can use your this library with any file format you want. It’s totally up to the user.
